name: Hello-world-workflow

on: push

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello World" && sleep 30
      - name: Print Hello fufu
        run: echo "Hello fufu"
